version: "3.7"
volumes:
  pgdata:
services:
  app:
    build: .
    container_name: blog
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - database
  database:
    image: postgres
    container_name: database_blog
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "blog"
    volumes:
      - pgdata:/data/postgres